### ISSUE TITLE
Hardcoded 'yarn_analysis_template' found in the Cloudformation template

### ISSUE THREAD

**Issue by joeyshub** [awslabs/migration-hadoop-to-emr-tco-simulator#6]
I found some hardcoded code in 'migration hadoop to emr tco simulator', not sure if this is intended.
Also, it looks like the permission for this 'yarn_analysis_template' is required in order to run Cloudformation successfully. Thanks !
![image](https://user-images.githubusercontent.com/19511481/211547562-2916b9e3-2548-4f6b-93bd-35d82a605661.png)

**Comment by coolhobbang** [comment]
Thank you for your comment. The account ID is the absolute path where QuickSight Analysis Template is located, and when you run CloudFormation file in the user account, the QuickSight Dashboard is automatically created from the template.
